name: Docker Image CI

on:
  push:
    branches: [ "main-sp2" ]
  pull_request:
    branches: [ "main-sp2" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker compose up --build -d

